### ISSUE TITLE
Websocket Port Listed Wrong in Release 0.2.0 Changelog

### ISSUE THREAD

**Issue by lesoreilly** [dementedmonkey/cj4-mcdu#10]
![image](https://user-images.githubusercontent.com/35707458/154336120-84f7b6e5-a96c-48f4-943e-7af1537fa9ab.png)

Source Code (and confirmed by running it) has the port as 8088.

Would recommend possibly changing to use 8380 to match the FBW now implemented Default port.

**Comment by dementedmonkey** [comment]
Oops, I'll fix that in the next release.

I intentionally used different ports from the FBW version.   If they used the same port, when you switched between planes you'd need to be careful about exiting one MCDU server before starting the other.   With separate ports, it doesn't matter if you have both running, each plane will only talk to the "proper" MCDU server.

**Comment by dementedmonkey** [comment]
The actual changelog file was fine, it was just the comment on the GitHub release, fixed.
