### ISSUE TITLE
please add sound when clicking button on remote CDU

### ISSUE THREAD

**Issue by r-flo-r** [dementedmonkey/cj4-mcdu#11]
first of all thanks a lot for this mod! its working fine.
would it be possible to add a sound, when you click a button on the remote CDU in the browser? just a small click or pop sound? thanks.

**Comment by dementedmonkey** [comment]
Looks like this is already present in FBW, and I'll just need to merge it:
https://github.com/flybywiresim/a32nx/pull/6694

**Comment by r-flo-r** [comment]
thanks a lot. sounds great.

PS: just a note, i am using your MCDU v0.2.0 together with the WT-CJ4 0.12.12 without any issues. maybe you can update to thi WT version as well in course of the button sound implementation.

**Comment by r-flo-r** [comment]
oh and are you gonna put this on flightsim.to?

**Comment by dementedmonkey** [comment]
FBW version didn't work that well on the iPad because Apple (click sound was significantly delayed).  I ended up with a different approach that feels much better.   This will be in 0.3.0.

**Comment by dementedmonkey** [comment]
I hadn't planned on uploading to flightsim.to, it seemed like folks were finding it here OK.   Maybe once the new CJ4 comes out.
