### ISSUE TITLE
Compatibility with JustFlight BAE146 ?

### ISSUE THREAD

**Issue by Delta-Charlie-DEV** [dementedmonkey/cj4-mcdu#19]
Hi,

I just read that the Justflight BAE 146 FMS is based on on the Working Title CJ4 FMS.

Any chance the remote MCDU would be compatible with the BAE ? That would be fantastic ... !

**Comment by dementedmonkey** [comment]
There are two obstacles to adding it in:
1. I don't own the BAE 146
2. Licensing might be tricky.   The mod requires delivering changed files that are part of the plane.   The Microsoft and WT licenses allow this, but I doubt JustFlight's license will allow this.
