### ISSUE TITLE
Is it possible to do something similar with G3000?

### ISSUE THREAD

**Issue by ilpav12** [dementedmonkey/cj4-mcdu#21]
Hello, and sorry for the unrelated question, but is it possible to recreate G3000/G5000 touchscreens?
They would be so much easier to use in a tablet by touch like the real ones.
I know that it is not the same thing as you don't have fixed keys as you operate directly on the screen, but maybe there is a way.
Thank you in advance

**Comment by dementedmonkey** [comment]
The thought has crossed my mind.    It would be a much more complicated project than the MCDU, and not something I'd be likely to take on anytime soon.
