### ISSUE TITLE
Doesn't work with CJ4 in AAU1 beta

### ISSUE THREAD

**Issue by neilenns** [dementedmonkey/cj4-mcdu#27]
Shocking exactly nobody I'm sure 🤣 But this mod doesn't work with the CJ4 refresh in the AAU1 beta that came out today.

**Comment by taipan303** [comment]
Damn, hope someone can figure it out before the final release goes public?

**Comment by neilenns** [comment]
It doesn't look promising. I don't see any HTML UI files at all in the new CJ4.

**Comment by neilenns** [comment]
Files should be here:

Which mods would that be? The html_ui stuff would now be found in `Official\xxxx\workingtitle-instruments-wt21`

**Comment by neilenns** [comment]
They also said in Discord that something like this would be a good candidate for the new plug-in model that will come (hopefully) with the full release in January.

**Comment by taipan303** [comment]
Yeah it's wearing me out the amount of time I need to spend maintaining all my MSFS aircraft in a flyable state 😂 more time modding and repairing stuff after updates than actual flying.

**Comment by dementedmonkey** [comment]
One of the WT devs pointed me in the right direction.  At first glance, it doesn't look like it will be that bad to make work (famous last words).

He also cautioned that with it being a beta, a lot of things are likely to change, and every beta update stands a good chance of breaking my mod.     I'll do what I can, but don't count on anything stable until after AAU1 release.

**Comment by neilenns** [comment]
> One of the WT devs pointed me in the right direction. At first glance, it doesn't look like it will be that bad to make work (famous last words).
> 
> He also cautioned that with it being a beta, a lot of things are likely to change, and every beta update stands a good chance of breaking my mod. I'll do what I can, but don't count on anything stable until after AAU1 release.

From the chatter I've had with them in Discord it sounds like a plug-in will be the proper way to do this at full release which will be nice and presumably less prone to breaking in future updates.

Until then... tweaking this to work with the AAU1 beta would be sweet :D

**Comment by neilenns** [comment]
I tried a flight today using the display popped out (instead of with this) and wow what a miserable experience 🤣 The performance was so bad I gave up and just closed the external window.

Lemme know if there's anything I can do to assist on this one, even if it's a temporary thing that has to be refreshed at release.

**Comment by dementedmonkey** [comment]
I managed to get it mostly working.   I still have to fix a few differences in how things are rendered and do some testing, but I should have something ready Soon™️

**Comment by taipan303** [comment]
Nice, thanks!

**Comment by neilenns** [comment]
The hero we needed!!!

**Comment by acealive75** [comment]
I use your MCDU addon also for the Bae146 (slightly modified some filepaths). I understand the FMC in the CJ4 is now different after AAU I ?

Does that affect the BAe146 FMC also ? And if not, would it be possibleto keep a version online that can work with the Bae146 ? 

Love your mod !

**Comment by dementedmonkey** [comment]
You should be able to continue to use the old mod with the 146.  I don't see any problem with installing the (modified) version of the 0.3.0 mod for the 146 alongside the new version for the new CJ4.    I'm not going to pull down the old versions or anything.

The CDU server is going to change, so you're going to need to be sure to run the proper version for the plane you're flying.   (For now.   That's a bigger project.)

**Comment by neilenns** [comment]
Works like a charm @dementedmonkey you're amazing!

I also updated my Electron app to use the updated code. It'll now pop open two windows as well, one for each display, and remember their positions independently. https://github.com/neilenns/Collins-FMS-3000-Display/releases/latest
