### ISSUE TITLE
Possible conflict with PilotEdge client for MSFS

### ISSUE THREAD

**Issue by tmmtaha75** [dementedmonkey/cj4-mcdu#3]
Hello: Would you be kind enough to download the free PilotEdge client for MSFS and check if there's a conflict with your mod? 
https://www.pilotedge.net/pages/download-software-msfs
Seems that both can't run at the same time:
(1) If the PilotEdge client is running, yours says looking for simulator while being used on a remote device on the same network.
(2) If your client is running, the PilotEdge client does not load and asks for an update despite using the latest version.
(3) Each client runs fine alone.

**Comment by dementedmonkey** [comment]
PilotEdge runs a local web server on 8081, which is the same as our web socket.    No good can come from that.

The app can switch ports, but the mod is hard-coded.   Eventually this should probably make its way onto the mod config screen so you can change it there.

I'll change the hardcoded values to 8088 to avoid the conflict with PilotEdge.

**Comment by tmmtaha75** [comment]
Thanks you! All good now.
