### ISSUE TITLE
No connection after newest AAU beta Update today?

### ISSUE THREAD

**Issue by Guenseli** [dementedmonkey/cj4-mcdu#30]
Hello,

I have had your great MCDU running before the AAU updates with 0.3.0.
Haven't tried it with the initial AAU beta and wanted to test it today.

I got now a new AAU beta 1.30.7. (?) but can't connect with your version 0.4.0

It says waiting for sim forever.

Do we need a new version for this new beta?

thx!

**Comment by dementedmonkey** [comment]
I just tried on 1.30.7.0 (the first update to the beta) and had no problem.

The files for the WT21 instrument did not change in this release, so I wouldn't expect anything to break.

Double check your content manager to be sure that the mod is still there, and see if restarting the flight doesn't fix it.

**Comment by neilenns** [comment]
I just gave this a try and it works fine as well.

**Comment by Guenseli** [comment]
Thx for the fast answer.

Still no luck. Restarted Computer, reinstalled Server and WASM Folder. Run Server as Admin
No idea what I could do else ...

**Comment by Guenseli** [comment]
thx for trying to help ...

After countless restarts of MSFS ... :upside_down_face:


I have emptied my community folder (except cj4 folder of course) and inserted back step by step.
Now the computer magic starts: it works now!

I have effectively done nothing as my community folder is the same as before the procedure.
But seems internally sth got in a better order.

**Comment by Guenseli** [comment]
Ok, case is not over ... it is my livery!

After that community folder orgy it seems I have choosen the default livery.
Then changed to my livery i normal use and it does not work any more.


However still can't say what I have to change now

**Comment by Guenseli** [comment]
Finally had success!
Fiddled around with my livery and got it solved (the exact way I do not know, I merged it with an existing, working livery)

thx for your work!!!
