### ISSUE TITLE
EDIT: Changed to "Waiting for Simulator"

### ISSUE THREAD

**Issue by Radio-War** [dementedmonkey/cj4-mcdu#37]
I keep getting this error when starting the server. And I apologize I now little more than how to install things. "Iconv-lite warning: decode()-ing strings is deprecated. Refer to https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding"

Any thoughts on why I would be getting this error?

edit: was able to clear it once I cleaned my community folder. But now it is stuck on Waiting for Sim. (Sim is open with CJ4 powered on)

**Comment by dementedmonkey** [comment]
That message has always been there and doesn't really hurt anything.    Normally it disappears really quickly (I never even noticed it myself).

The "Waiting for simulator..." means the mod isn't talking to the MCDU server.   Things to look at
* Make sure you have the right version of the software.  0.3.0 if you're on SU111, 0.5.0 if you're on the AAU1 beta
* Make sure the mod files from that version are in your community folder, and that you've deleted the old mod if you upgraded.

**Comment by Radio-War** [comment]
Yes, I currently have a clean community folder with just the 0.5.0 folder. I am running the server in administrator mode.

I opened the manifest file to double check. ""package_version":  "0.5.0","

I never tried 0.3.0 with WT. 
![Screenshot 2022-12-21 221315](https://user-images.githubusercontent.com/49008141/209136338-4a03a022-e4f2-45fc-96de-07bea92c791d.png)

EDIT: Simulator is up and running. Loaded into CJ4 and powered on with engines running. Open Server and it stays stuck on "Waiting for Simulator"

**Comment by dementedmonkey** [comment]
This might be a conflict with something else running on your system.   Can you gather some more data for me?

With Flight Simulator and the MCDU server running...
* Start a Powershell command prompt **as administrator**
* Run the command `netstat -n -p tcp -a -b | select-string -pattern 8088 -context 0,1`
* Paste the command output here

**Comment by dementedmonkey** [comment]
Release [0.5.1](https://github.com/dementedmonkey/cj4-mcdu/releases/tag/v0.5.1) will now check for port conflicts when starting the MCDU server ( #39 ).    We can't do anything about the program that opened the port first, but the error will let you know to not expect things to work.
