### ISSUE TITLE
? Also working with Version 1.32.7.0 ?

### ISSUE THREAD

**Issue by Mocko6659** [dementedmonkey/cj4-mcdu#42]
I was wondering if the Version 0.5.1 is also working with the actual version of MSFS (1.32.7.0). At the Moment the Server says "waiting for simulator" and I dont know if I'm doing something wrong or its just meant to be not working. ;D

Thanks for your help,
Mocko

**Comment by dementedmonkey** [comment]
Yes, it works with the current released version as well as AAU2 beta (1.33.5.0)

Some things to try:
* Make sure you copied the `z-dementedmonkey-cj4-mcdu` into the proper `Community` folder.
* If you still have the WT mod for the CJ4 installed, remove it.   It's now built directly into the sim.
* It doesn't connect until you actually start a flight with the CJ4

**Comment by Mocko6659** [comment]
Perfect! The Mod was installed. Thank you for your help!! :)
