### ISSUE TITLE
Co-pilot MCDU

### ISSUE THREAD

**Issue by diddi-** [dementedmonkey/cj4-mcdu#43]
First off, thanks for making this mod. Works great with CJ4 AAU2!

Now that the CJ4 has two individual MCDU, would it be possible to have two servers running on separate ports or something that connects to each of the MCDU? 

The second MCDU controls the co-pilot PFD/MFD and it would be useful as well when flying in a shared cockpit.

**Comment by neilenns** [comment]
Dual displays have been supported since December. See the "[Multiple screens](https://github.com/dementedmonkey/cj4-mcdu#multiple-screens)" section of the readme.

**Comment by diddi-** [comment]
Oh my, sorry! Totally missed that part. Thanks for pointing it out.
