### ISSUE TITLE
Update for SU15

### ISSUE THREAD

**Issue by dementedmonkey** [dementedmonkey/cj4-mcdu#46]
SU15 beta has a new plugin system for the MCDU.

Need to change things to use the new system.   This might need to wait a bit for documentation/SDK from WT.

**Comment by neilenns** [comment]
Let me know if you need help testing the changes once WT publishes the docs, am happy to help

**Comment by dementedmonkey** [comment]
@neilenns I was able to figure out a lot from how the other instruments worked, it's still hacky but it's working for me.  Can you give this a try?   (0.6.0-beta1)

**Comment by neilenns** [comment]
Forgot I'm not in the beta 😅 Installing it now, should be able to give this a go sometime tomorrow.

**Comment by neilenns** [comment]
Ok I tried it tonight. Seems to work fine. All of the screens I brought up displayed correctly, and I used a bunch of the buttons in the MCDU Server app and they worked. I forgot to test pilot/co-pilot though.

How terrible were the changes? I'll have to update the wrapper app I've got too.

**Comment by dementedmonkey** [comment]
Thanks for testing!

The changes were surprisingly small, mostly replacing my hook code with new plugin hook code.

Your wrapper app shouldn't have to change.   The client is the same, it was only the mod that changed.

**Comment by neilenns** [comment]
So I'm not sure if this is related to the add-on, but today I did a full flight and had an issue where my flight plan cleared out completely after I sent the perf data to the PFDs. The origin and destination airports, and the entire route, just vanished.

I wasn't able to reproduce the issue when I tried a second flight, but I have noticed that sometimes the entire displays will redraw.

I've mentioned it in the WT Discord, but thought I'd mention it here as well on the slim chance it's related to the plug-in model.

**Comment by r-flo-r** [comment]
Hi. would like to ask for an update about SU15 compatibility, as SU15 has now officialy been released. Thanks and thanks for this great addon.

**Comment by neilenns** [comment]
> Hi. would like to ask for an update about SU15 compatibility, as SU15 has now officialy been released. Thanks and thanks for this great addon.

Have you tried the latest beta release? It worked fine with SU15 beta, should be fine with the release version as well. 

https://github.com/dementedmonkey/cj4-mcdu/releases/tag/v0.6.0-beta1

**Comment by r-flo-r** [comment]
thanks. the beta version works. i did no flight, just loaded one quickly. 
Maybe it would make sense to point out the beta version on the main side of this mod. i just have seen there, that there was a note that the mod will not work with SU15-beta. but i did not recognize, that there was a beta.

thank you
