### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by krxs747** [dementedmonkey/cj4-mcdu#6]
How do I install this? The instructions do not match contents in the ZIP folder. I go to follow the procedure in the folder downloaded but see no "z" folder nor could I find an .exe to get the application started. I downloaded the master. Is there something I am doing wrong?

**Comment by neilenns** [comment]
Sounds like you downloaded the entire GitHub repo. Try downloading the release from here: https://github.com/dementedmonkey/cj4-mcdu/releases/download/v0.2.0/cj4-mcdu-0.2.0.zip
