### ISSUE TITLE
Blank screen when sim disconnects

### ISSUE THREAD

**Issue by neilenns** [dementedmonkey/cj4-mcdu#9]
Right now after doing a flight and closing Flight Simulator the last received text is still displayed. It'd be nice instead to have this detect the disconnect and show a blank screen instead.

**Comment by dementedmonkey** [comment]
I thought about the same thing.   I don't know that I can get a reliable indication that the sim has exited, but I should be able to put in a timeout that will blank the screen if it doesn't hear from the sim in 10 seconds or something.

**Comment by neilenns** [comment]
I spent some time on this after I opened it and didn't have much luck finding a way to do it by straight disconnect messages. Blanking after no communication for a bit would likely work fine.
